---
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      kpn:
        ipv4_address: 172.16.238.2

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.238.3
      KAFKA_ZOOKEEPER_CONNECT: 172.16.238.2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.16.238.3:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      kpn:
        ipv4_address: 172.16.238.3

  kafka-rest:
    image: confluentinc/cp-kafka-rest
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: 172.16.238.3:9092
      KAFKA_REST_ZOOKEEPER_CONNECT: 172.16.238.2:2181
      KAFKA_REST_HOST_NAME: 172.16.238.4
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: 'GET,POST,PUT,DELETE,OPTIONS'
    ports:
      - 8082:8082
    depends_on:
      - kafka
    networks:
      kpn:
        ipv4_address: 172.16.238.4

  topics-ui: # TODO: topics-ui does not work, don't know why
    image: landoop/kafka-topics-ui
    ports:
      - 8000:8000
    environment:
      KAFKA_REST_PROXY_URL: http://172.16.238.4:8082
    depends_on:
      - kafka-rest
    networks:
      kpn:
        ipv4_address: 172.16.238.5

networks:
  kpn:
    # use the bridge driver, but enable IPv6
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
